# Generated by Django 5.2 on 2025-05-01 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('url_imagen', models.TextField()),
                ('id_imagen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoArticuloModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('url_imagen', models.TextField()),
                ('id_imagen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nickname', models.TextField(unique=True)),
                ('password', models.TextField(unique=True)),
                ('t2f_url', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_articulo', to='database_backend.articulomodel')),
            ],
        ),
        migrations.AddField(
            model_name='articulomodel',
            name='id_articulo_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_articulo_tipo', to='database_backend.tipoarticulomodel'),
        ),
    ]
