# Generated by Django 5.2 on 2025-05-01 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulomodel',
            name='id_articulo_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo_tipos', to='database_backend.tipoarticulomodel'),
        ),
        migrations.AlterField(
            model_name='notamodel',
            name='id_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='database_backend.articulomodel'),
        ),
    ]
