# Generated by Django 5.2 on 2025-05-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_backend', '0002_alter_articulomodel_id_articulo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoarticulomodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
