# Generated by Django 5.2 on 2025-05-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_backend', '0003_alter_tipoarticulomodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulomodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notamodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
