# Generated by Django 5.2 on 2025-05-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_backend', '0004_alter_articulomodel_id_alter_notamodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioModel',
        ),
    ]
