# Generated by Django 5.2 on 2025-05-03 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_backend', '0005_delete_usuariomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulomodel',
            name='id_articulo_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='database_backend.tipoarticulomodel'),
        ),
        migrations.AlterField(
            model_name='notamodel',
            name='id_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='database_backend.articulomodel'),
        ),
    ]
