# Generated by Django 5.2 on 2025-05-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_backend', '0006_alter_articulomodel_id_articulo_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulomodel',
            name='id_imagen',
        ),
        migrations.RemoveField(
            model_name='tipoarticulomodel',
            name='id_imagen',
        ),
        migrations.AlterField(
            model_name='articulomodel',
            name='url_imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tipoarticulomodel',
            name='url_imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
