# Generated by Django 5.2 on 2025-05-04 19:50

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_backend', '0007_remove_articulomodel_id_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulomodel',
            name='url_imagen',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tipoarticulomodel',
            name='url_imagen',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='images/'),
        ),
    ]
